### ISSUE TITLE
Process crashes if there is a missing dependency

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe-cli#5]
Note that currently the only dependency is Git.

```
/usr/lib/node_modules/apostrophe-cli/lib/util.js:33
  console.log(dep + ' not found'.red);
              ^
ReferenceError: dep is not defined
    at Object.util.missingDependency (/usr/lib/node_modules/apostrophe-cli/lib/util.js:33:15)
    at Object.util.checkDependencies (/usr/lib/node_modules/apostrophe-cli/lib/util.js:43:12)
    at Object.<anonymous> (/usr/lib/node_modules/apostrophe-cli/bin/apostrophe:10:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by jth-** [comment]
Resolved in master.
